### ISSUE TITLE
How can I support the format like GIF_FORMAT_LONG?

### ISSUE THREAD

**Issue by Sieyalixnet** [jcmb/GGF#1]
I get some .ggf format files, half of them are in GIF_FORMAT_LONG instead of GIF_FORMAT_FLOAT type. I want to parse them, so I modify the unpack in the `parseGrid` function, like:

```python
longs=list(unpack("<{}l".format(self._LongGridSize),ggfFile[start: end]))
```

I don't think the output is correct. Can you give some advice or support another type?
This repository gives me much help, thank you very much.

**Comment by jcmb** [comment]
Do you have an example of one, or at least the name of one.

**Comment by Sieyalixnet** [comment]
Thanks your reply,
I upload these invalid files on my google drive now,
[https://drive.google.com/drive/folders/1R75zYHafTotumOZ1q6rJBwsm7WHaiTn0?usp=sharing](https://drive.google.com/drive/folders/1R75zYHafTotumOZ1q6rJBwsm7WHaiTn0?usp=sharing)
I print the error in each text file.

These files are downloaded from a software, I don't know how they can get them.
For most of files, this repository works. Only these files are invalid.

**Comment by jcmb** [comment]
I have updated to tool to handle it, and scaled data.

Note cgg2013n.ggf looks OK.

Version: 1
Name: Canada CGG2013 (NAD83)
Latitude:  Min: 41.016666666666666   Max: 83.98333333333333
Longitude: Min: 218.01666666666668   Max: 311.98333333333335
Interval: Lat: 0.03333333333333333   Max: 0.03333333333333333
GridSize: Lat: 1290   Max: 2820
Latitude:  Min: 41.016666666666666   Max: 83.98333333333333 Max Step: 83.98333333333333
Longitude: Min: 218.01666666666668   Max: 311.98333333333335 Max Step: 311.98333333333335
Poles:     North: 0.0   South: 0.0
Missing: 0.0
Scalar:  0.0
Window:  3
Min Values:  -48.998 from Footer -48.998
Max Values:  41.664 from Footer 41.664


HT2_1997_GEO.GGF is incorrect.
The missing value is set to 32767 but the file has a missing value of 9999

Around the edges of the model you will have errors, the file says there is data with a separation of 9999m and if you go into areas that should not have data you will get a separation of 9999.

Version: 0
Name: HT-1997
Latitude:  Min: 41.016666666666666   Max: 83.98333333333333
Longitude: Min: 218.01666666666668   Max: 311.98333333333335
Interval: Lat: 0.03333333333333333   Max: 0.03333333333333333
GridSize: Lat: 1290   Max: 2820
Latitude:  Min: 41.016666666666666   Max: 83.98333333333333 Max Step: 83.98333333333333
Longitude: Min: 218.01666666666668   Max: 311.98333333333335 Max Step: 311.98333333333335
Poles:     North: 0.0   South: 0.0
Missing: 32767.0
Scalar:  1000.0
Window:  3
Min Values:  -49.432
Max Values:  9999.000

Where did that one come from?

**Comment by Sieyalixnet** [comment]
Thank you very much.

These data are downloaded from a software which belongs to a company producing like RTK and some other types of surveying and mapping devices in China. I think they collected these data from the internet or other companies.
